--EXCLUIR VINCULOS FKs
ALTER TABLE portal_cadastro.REGRA DROP CONSTRAINT fk_cd_tipo_regra;
ALTER TABLE portal_cadastro.REGRA DROP CONSTRAINT fk_cd_tipo_regra_ant;
ALTER TABLE portal_cadastro.REGRA DROP CONSTRAINT fk_cd_modulo_regra;
ALTER TABLE portal_cadastro.CONTROLE_PRODUTO DROP CONSTRAINT fk_cd_tipo_regra_controle;
ALTER TABLE portal_cadastro.CONTROLE_PRODUTO DROP CONSTRAINT fk_cd_modulo_controle;

--------
--TIPO--
--------

DROP TABLE portal_cadastro.TIPO;
CREATE TABLE portal_cadastro.TIPO(

CD_TIPO             INT NOT NULL,
DS_TIPO             VARCHAR(100) NOT NULL,
SN_ATIVO            VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

CONSTRAINT check_sn_ativo_tipo CHECK (SN_ATIVO IN ('S', 'N')),
CONSTRAINT pk_cd_tipo PRIMARY KEY (CD_TIPO)
--CONSTRAINT fk_cd_setor FOREIGN KEY (CD_SETOR) REFERENCES setor(CD_SETOR)

);

DROP SEQUENCE seq_cd_tipo; 
CREATE SEQUENCE seq_cd_tipo 
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--INSERT TIPO
INSERT INTO portal_cadastro.TIPO
SELECT seq_cd_tipo.NEXTVAL, 
'MEDICAMENTOS' AS DS_TIPO,
'S' AS SN_ATIVO,
'HSSAMPAIO' AS CD_USUARIO_CADASTRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

----------
--MODULO--
----------

DROP TABLE portal_cadastro.MODULO;
CREATE TABLE portal_cadastro.MODULO(

CD_MODULO           INT NOT NULL,
DS_MODULO           VARCHAR(100) NOT NULL,
SN_ATIVO            VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

CONSTRAINT check_sn_ativo_modulo CHECK (SN_ATIVO IN ('S', 'N')),
CONSTRAINT pk_cd_modulo PRIMARY KEY (CD_MODULO)
--CONSTRAINT fk_cd_setor FOREIGN KEY (CD_SETOR) REFERENCES setor(CD_SETOR)

);

DROP SEQUENCE seq_cd_modulo; 
CREATE SEQUENCE seq_cd_modulo 
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--INSERT MODULO
INSERT INTO portal_cadastro.MODULO
SELECT seq_cd_modulo.NEXTVAL, 
'PRODUTO' AS DS_MODULO,
'S' AS SN_ATIVO,
'HSSAMPAIO' AS CD_USUARIO_CADASTRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

INSERT INTO portal_cadastro.MODULO
SELECT seq_cd_modulo.NEXTVAL, 
'BRASINDICE' AS DS_MODULO,
'S' AS SN_ATIVO,
'HSSAMPAIO' AS CD_USUARIO_CADASTRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

---------
--REGRA--
---------

DROP TABLE portal_cadastro.REGRA;
CREATE TABLE portal_cadastro.REGRA(

CD_REGRA            INT NOT NULL,
CD_TIPO             INT NOT NULL,
CD_MODULO           INT NOT NULL,
CD_MODULO_ANTERIOR  INT NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

CONSTRAINT pk_cd_regra PRIMARY KEY (CD_REGRA),
CONSTRAINT fk_cd_tipo_regra FOREIGN KEY (CD_TIPO) REFERENCES TIPO(CD_TIPO),
CONSTRAINT fk_cd_tipo_regra_ant FOREIGN KEY (CD_TIPO) REFERENCES TIPO(CD_TIPO),
CONSTRAINT fk_cd_modulo_regra FOREIGN KEY (CD_MODULO) REFERENCES MODULO(CD_MODULO)

);

DROP SEQUENCE seq_cd_regra; 
CREATE SEQUENCE seq_cd_regra
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--INSERT REGRA
INSERT INTO portal_cadastro.REGRA
SELECT seq_cd_regra.NEXTVAL, 
1 AS CD_TIPO, --MEDICAMENTO
1 AS CD_MODULO, --PRODUTO
0 AS CD_MODULO_ANTERIOR, --NÃO TEM É O PRIMEIRO
'HSSAMPAIO' AS CD_USUARIO_CADASTRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

INSERT INTO portal_cadastro.REGRA
SELECT seq_cd_regra.NEXTVAL, 
1 AS CD_TIPO, --MEDICAMENTO
2 AS CD_MODULO, --BRASINDICE
1 AS CD_MODULO_ANTERIOR, --PRODUTO
'HSSAMPAIO' AS CD_USUARIO_CADASTRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

--------------------
--CONTROLE_PRODUTO--
--------------------

DROP TABLE portal_cadastro.CONTROLE_PRODUTO;
CREATE TABLE portal_cadastro.CONTROLE_PRODUTO(

CD_CONTROLE_PRODUTO INT NOT NULL,
CD_PRODUTO          INT NOT NULL,
CD_TIPO             INT NOT NULL,
CD_MODULO_PENDENCIA INT NOT NULL,
SN_FINALIZADO       VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

CONSTRAINT check_sn_ativo_controle CHECK (SN_FINALIZADO IN ('S', 'N')),
CONSTRAINT pk_cd_controle_produto PRIMARY KEY (CD_CONTROLE_PRODUTO),
CONSTRAINT fk_cd_tipo_regra_controle FOREIGN KEY (CD_TIPO) REFERENCES TIPO(CD_TIPO),
CONSTRAINT fk_cd_modulo_controle FOREIGN KEY (CD_MODULO_PENDENCIA) REFERENCES MODULO(CD_MODULO)

);

DROP SEQUENCE seq_cd_controle_produto; 
CREATE SEQUENCE seq_cd_controle_produto
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

-------------------------
--SEQ_CD_TEMP_UNIVERSAL--
-------------------------

DROP SEQUENCE seq_cd_temp_universal; 
CREATE SEQUENCE seq_cd_temp_universal
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--SELECT portal_cadastro.seq_cd_temp_universal.NEXTVAL FROM DUAL;

----------------
--TEMP_UNI_PRO--
----------------

DROP TABLE portal_cadastro.TEMP_UNI_PRO;

CREATE TABLE portal_cadastro.TEMP_UNI_PRO AS
SELECT * 
FROM dbamv.UNI_PRO
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_UNI_PRO 
MODIFY (CD_PRODUTO NULL);

ALTER TABLE portal_cadastro.TEMP_UNI_PRO
ADD CONSTRAINT TEMP_UNI_PRO_UK UNIQUE (CD_PRODUTO, SN_ATIVO, DS_UNIDADE);

DELETE FROM portal_cadastro.TEMP_UNI_PRO
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_UNI_PRO;

----------------
--TEMP_LAB_PRO--
----------------

DROP TABLE portal_cadastro.TEMP_LAB_PRO;

CREATE TABLE portal_cadastro.TEMP_LAB_PRO AS
SELECT * 
FROM dbamv.LAB_PRO
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_LAB_PRO
ADD CONSTRAINT TEMP_LAB_PRO_PK UNIQUE (CD_PRODUTO, CD_LABORATOR);

DELETE FROM portal_cadastro.TEMP_LAB_PRO
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_LAB_PRO;

-----------------
--TEMP_SUBS_PRO--
-----------------

DROP TABLE portal_cadastro.TEMP_SUBS_PRO;

CREATE TABLE portal_cadastro.TEMP_SUBS_PRO AS
SELECT SUBS_PRO.*, 'S' AS SN_PRINCIPAL 
FROM dbamv.SUBS_PRO
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_SUBS_PRO
ADD CONSTRAINT TEMP_SUBS_PROPK UNIQUE (CD_SUBSTANCIA, CD_PRODUTO);

DELETE FROM portal_cadastro.TEMP_SUBS_PRO
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_SUBS_PRO;


-----------------
--TEMP_IMP_BRA---
-----------------

DROP TABLE portal_cadastro.TEMP_IMP_BRA;

CREATE TABLE portal_cadastro.TEMP_IMP_BRA AS
SELECT *
FROM dbamv.IMP_BRA
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_IMP_BRA
ADD CONSTRAINT TEMP_IMP_BRA_UK UNIQUE (CD_PRO_FAT, CD_TAB_FAT);

DELETE FROM portal_cadastro.TEMP_IMP_BRA
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_IMP_BRA;

-----------------
--TEMP_MAT_PROC--
-----------------

DROP TABLE portal_cadastro.TEMP_MAT_PROC;

CREATE TABLE portal_cadastro.TEMP_MAT_PROC AS
SELECT * 
FROM dbamv.MAT_PROC
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_MAT_PROC 
ADD CONSTRAINT MAT_PROC_UK UNIQUE (CD_PRO_FAT, CD_TAB_FAT);

ALTER TABLE portal_cadastro.TEMP_MAT_PROC 
ADD CHECK (TP_CUSTO IN ( '1' , '2' ));

DELETE FROM portal_cadastro.TEMP_MAT_PROC
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_MAT_PROC;

-------------
--TEMP_TUSS--
-------------

DROP TABLE portal_cadastro.TEMP_TUSS;

CREATE TABLE portal_cadastro.TEMP_TUSS AS
SELECT * 
FROM dbamv.TUSS
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_TUSS 
ADD CONSTRAINT TUSS_PROC_UK UNIQUE (CD_TUSS,CD_PRO_FAT);

DELETE FROM portal_cadastro.TEMP_TUSS
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_TUSS;

---------------
--TEMP_COMPON--
---------------

DROP TABLE portal_cadastro.TEMP_COMPON;

CREATE TABLE portal_cadastro.TEMP_COMPON AS
SELECT * 
FROM dbamv.COMPON
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_COMPON 
ADD CONSTRAINT COMPON_COMPONENTE_APL_UK UNIQUE (CD_TIP_PRESC,CD_TIP_PRESC_COMPONENTE,CD_FOR_APL);

DELETE FROM portal_cadastro.TEMP_COMPON
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_COMPON;

--------------------------
--TEMP_TIP_PRESC_FOR_APL--
--------------------------

DROP TABLE portal_cadastro.TEMP_TIP_PRESC_FOR_APL;

CREATE TABLE portal_cadastro.TEMP_TIP_PRESC_FOR_APL AS
SELECT * 
FROM dbamv.TIP_PRESC_FOR_APL
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_TIP_PRESC_FOR_APL 
ADD CONSTRAINT TEMP_TIP_PRESC_FOR_APL_UK UNIQUE (CD_TIP_PRESC, CD_FOR_APL);

DELETE FROM portal_cadastro.TEMP_TIP_PRESC_FOR_APL
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_COMPON;

--------------------------
--TEMP_TIP_PRESC_FOR_APL--
--------------------------

DROP TABLE portal_cadastro.TEMP_PW_CONTROLE_DOSE;

CREATE TABLE portal_cadastro.TEMP_PW_CONTROLE_DOSE AS
SELECT * 
FROM dbamv.PW_CONTROLE_DOSE
WHERE ROWNUM BETWEEN 1 AND 10000;

DELETE FROM portal_cadastro.TEMP_PW_CONTROLE_DOSE
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_PW_CONTROLE_DOSE;

--------------------------
--TEMP_TIP_PRESC_TIP_FRE--
--------------------------

DROP TABLE portal_cadastro.TEMP_TIP_PRESC_TIP_FRE;

CREATE TABLE portal_cadastro.TEMP_TIP_PRESC_TIP_FRE AS
SELECT * 
FROM dbamv.TIP_PRESC_TIP_FRE
WHERE ROWNUM BETWEEN 1 AND 10000;

ALTER TABLE portal_cadastro.TEMP_TIP_PRESC_TIP_FRE 
ADD CONSTRAINT TEMP_TIP_PRESC_TIP_FRE_UK UNIQUE (CD_TIP_PRESC, CD_TIP_FRE);

DELETE FROM portal_cadastro.TEMP_TIP_PRESC_TIP_FRE
WHERE 1 = 1;

--SELECT * FROM portal_cadastro.TEMP_TIP_PRESC_TIP_FRE;

----------
--COMMIT--
----------

COMMIT;
