--EXCLUIR VINCULOS FKs
--ALTER TABLE portal_cadastro.REGRA DROP CONSTRAINT fk_cd_tipo_regra;

--------
--TIPO--
--------

DROP TABLE portal_cadastro.TIPO;
CREATE TABLE portal_cadastro.TIPO(

CD_TIPO             INT NOT NULL,
DS_TIPO             VARCHAR(100) NOT NULL,
SN_ATIVO            VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

CONSTRAINT check_sn_ativo_tipo CHECK (SN_ATIVO IN ('S', 'N')),
CONSTRAINT pk_cd_tipo PRIMARY KEY (CD_TIPO)
--CONSTRAINT fk_cd_setor FOREIGN KEY (CD_SETOR) REFERENCES setor(CD_SETOR)

);

DROP SEQUENCE seq_cd_tipo; 
CREATE SEQUENCE seq_cd_tipo 
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;
